name: Black Check and Tests

on:
  pull_request:
    branchs:
      - master
  push:
    branchs:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python_version: ['3.7', '3.8']
        os: [ubuntu-latest, macOS-latest]
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}
      - uses: actions/cache@v1
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python_version }}-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python_version }}-
      - uses: actions/cache@v1
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ matrix.python_version }}-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python_version }}-
      - uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: pipenv --python ${{ matrix.python_version }} sync -d
      - name: Lint with Black
        run: pipenv run black --check events_protocol
      - name: Tests
        run: pipenv run pytest --cov=events_protocol tests/
